DROP DATABASE IF EXISTS chat_room;
CREATE DATABASE chat_room CHARACTER SET utf8 COLLATE utf8_general_ci;
USE chat_room;

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL,
  password VARCHAR(32) NOT NULL,
  time_sign_up TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  contact_id INT NOT NULL,
  type ENUM('0', '1') DEFAULT '0', -- ‘0’：联系人，‘1’：群组
  remarks VARCHAR(32),
  msg_unread INT DEFAULT 0,
  status ENUM('0', '1') DEFAULT '0', -- '0'：未加入聊天列表，‘1’：已加入聊天列表
  time_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_group (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  group_name VARCHAR(32) NOT NULL,
  time_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE group_user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  time_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE msg (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type ENUM('0', '1', '2') DEFAULT '1', -- ‘-1’: 文本，‘0’: 媒体资源
  content VARCHAR(256) NOT NULL,
  receiver INT NOT NULL,
  sender INT NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);