DROP DATABASE IF EXISTS chat_room;
CREATE DATABASE chat_room CHARACTER SET utf8 COLLATE utf8_general_ci;
USE chat_room;

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL,
  password VARCHAR(32) NOT NULL,
  time_sign_up TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  contact_id INT NOT NULL,
  time_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE group (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  time_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE group_user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  time_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE msg (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type ENUM('0', '1', '2') DEFAULT '1', -- ‘-1’: 文本，‘0’: 媒体资源
  content VARCHAR(256) NOT NULL,
  receiver INT NOT NULL,
  sender INT NOT NULL,
  status ENUM('0', '1'), -- '0': 未读，‘1’：已读
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);